name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt
      
      - name: Install Python dev dependencies
        run: python3 -m pip install -r dev-requirements.txt

      # - name: Run tests
      #   run: bash run_tests.sh

      - name: Build
        run: bash make_distrib.sh

      # - name: Publish package to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_TEST_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
