name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: apt-get install git
      
      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt
      
      - name: Install Python dev dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Run tests
        run: bash run_tests.sh
